# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

resolver: lts-3.15

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: 2098038b9316e2a5d9bed54c61bf4582469d9e06
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-cuda.git
    commit: 1ff609b498041ef6c4c49d89b70ba06c3fbde010
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 465a336be2c891682c263051e154c3134a58bbd5
  extra-dep: true
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx
    - accelerate-llvm-multidev

- location:
    git:    https://github.com/tmcdonell/accelerate-random.git
    commit: 0accd7ef61e509b68795faa5bac790e4fd937d02
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-io.git
    commit: 64eeb44d899a259ff2f6e325dfd107f004e5c4e2
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/cuda.git
    commit: 4153ab41fdea3dcc205c4d8c12734f1c2322ff6d
  extra-dep: true


extra-deps:
- chaselev-deque-0.5.0.5
- libffi-0.1
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
- sfmt-0.1.1
- unique-0

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    debug: true
  accelerate-cuda:
    debug: true
  accelerate-llvm:
    debug: true
    chase-lev: true
  accelerate-llvm-native:
    debug: true
  accelerate-llvm-ptx:
    debug: true
  llvm-general:
    shared-llvm: true


# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# vim: nospell
