# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

resolver: lts-3.15

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: 8355b8c75d9ecc0fcabd34f003bd58ddde20af64
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-cuda.git
    commit: 1ff609b498041ef6c4c49d89b70ba06c3fbde010
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 465a336be2c891682c263051e154c3134a58bbd5
  extra-dep: true
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx
    - accelerate-llvm-multidev

- location:
    git:    https://github.com/tmcdonell/accelerate-random.git
    commit: 925ed7425afc864ec730175f458225ad84974125
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/cuda.git
    commit: bce7f414fd96f8841ae81aaa2151e2c7dc7e954e
  extra-dep: true


extra-deps:
- unique-0
- chaselev-deque-0.5.0.5
- llvm-general-pure-3.5.0.0
- llvm-general-3.5.1.1
- libffi-0.1
- cuda-0.7.1.0

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    debug: true
  accelerate-cuda:
    debug: true
  accelerate-llvm:
    debug: true
    chase-lev: true
  accelerate-llvm-native:
    debug: true
  accelerate-llvm-ptx:
    debug: true
  llvm-general:
    shared-llvm: true


# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# vim: nospell
